spring:
  application:
    name: coffee-machine

  datasource:
    username: postgres
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://localhost:5432/test
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: false